# Generated by Django 3.2.3 on 2021-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_clients', models.CharField(max_length=100)),
                ('prenom_clients', models.CharField(max_length=100)),
                ('mail_clients', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_clients', models.CharField(max_length=20)),
                ('photo_clients', models.ImageField(default='/static/img/avatar.png', null=True, upload_to='images')),
                ('date_naissance_clients', models.DateField(blank=True, null=True)),
                ('adresse_clients', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ville_clients', models.CharField(blank=True, max_length=100, null=True)),
                ('departement_clients', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal_clients', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'clients',
            },
        ),
    ]
