# Generated by Django 3.2.3 on 2021-06-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoints',
            fields=[
                ('projet_checks', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projets.projets')),
                ('check1', models.BooleanField(blank=True, default='', null=True)),
                ('check2', models.BooleanField(blank=True, default='', null=True)),
                ('check3', models.BooleanField(blank=True, default='', null=True)),
                ('check4', models.BooleanField(blank=True, default='', null=True)),
                ('check5', models.BooleanField(blank=True, default='', null=True)),
                ('check6', models.BooleanField(blank=True, default='', null=True)),
                ('check7', models.BooleanField(blank=True, default='', null=True)),
                ('check8', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], default='', max_length=3, null=True)),
                ('check9', models.BooleanField(blank=True, default='', null=True)),
                ('check10', models.BooleanField(blank=True, default='', null=True)),
                ('check11', models.BooleanField(blank=True, default='', null=True)),
                ('check12', models.BooleanField(blank=True, default='', null=True)),
                ('check13', models.BooleanField(blank=True, default='', null=True)),
                ('check14', models.BooleanField(blank=True, default='', null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
