# Generated by Django 3.2.3 on 2021-06-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entites', models.CharField(choices=[('Montauban & Fils', 'Montauban & Fils'), ('Funeraire Sud Charente', 'Funeraire Sud Charente'), ('Gauthier', 'Gauthier'), ('Façade Sud Charente', 'Façade Sud Charente')], default='Montauban & Fils', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_debut_projets', models.DateField(default=django.utils.timezone.now)),
                ('date_fin_provisoire', models.DateField(blank=True, default=None, null=True)),
                ('description_projets', models.CharField(max_length=255)),
                ('nom_projets', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_projets', models.CharField(max_length=255)),
                ('code_postal_projets', models.IntegerField()),
                ('ville_projets', models.CharField(max_length=100)),
                ('departement_projets', models.CharField(max_length=100)),
                ('projet_status_projets', models.CharField(choices=[('En attente', 'En attente'), ('A planifie', 'A planifie'), ('Planifie', 'Planifie'), ('Realises', 'Realises')], default='A planifie', max_length=25)),
                ('entites_projets', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projets.entites')),
                ('projet_clients', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('starter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoChantier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chantier_photo', models.ImageField(upload_to='photochantier')),
                ('projet_photo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projets.projets')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre_devis', models.CharField(max_length=255)),
                ('numero_devis', models.CharField(default=None, max_length=20)),
                ('date_insertion_devis', models.DateField(default=django.utils.timezone.now)),
                ('date_creation_devis', models.DateField()),
                ('pdf_devis', models.FileField(upload_to='pdfdevis')),
                ('entite_devis', models.ManyToManyField(default=None, to='projets.Entites')),
                ('projet_devis', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projets.projets')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeLivraison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_insertion_bl', models.DateField(default=django.utils.timezone.now)),
                ('date_bl', models.DateField()),
                ('pdf_bl', models.FileField(upload_to='pdfbc')),
                ('entite_bl', models.ManyToManyField(default=None, to='projets.Entites')),
                ('projet_bl', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projets.projets')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_insertion_bc', models.DateField(default=django.utils.timezone.now)),
                ('date_bc', models.DateField()),
                ('pdf_bc', models.FileField(upload_to='pdfbc')),
                ('entite_bc', models.ManyToManyField(default=None, to='projets.Entites')),
                ('projet_bc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projets.projets')),
            ],
        ),
    ]
