# Generated by Django 3.2.3 on 2021-06-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='date_creation_devis',
        ),
    ]
