# Generated by Django 3.2.3 on 2021-06-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_remove_devis_date_creation_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='entite_devis',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='projets.Entites'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero_devis',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='pdf_devis',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfdevis'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='projet_devis',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projets.projets'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='titre_devis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
