# Generated by Django 3.2.3 on 2021-06-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_auto_20210605_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='pdf_devis',
            field=models.FileField(default=None, upload_to='pdfdevis'),
        ),
    ]
