# Generated by Django 3.2.3 on 2021-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_alter_devis_pdf_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='pdf_devis',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfdevis'),
        ),
    ]
