# Generated by Django 3.2.3 on 2021-06-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_alter_devis_pdf_devis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommande',
            name='entite_bc',
        ),
        migrations.RemoveField(
            model_name='bondelivraison',
            name='entite_bl',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='entite_devis',
        ),
    ]
