# Generated by Django 3.2.3 on 2021-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_auto_20210606_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='nummero_bc',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='bondelivraison',
            name='nummero_bl',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
