# Generated by Django 3.2.3 on 2021-06-08 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_auto_20210608_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='numero_devis',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='pdf_devis',
            field=models.FileField(default=None, upload_to='pdfdevis'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='projet_devis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projets.projets'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='titre_devis',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
