# Generated by Django 3.2.3 on 2021-06-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0008_auto_20210608_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bondecommande',
            old_name='nummero_bc',
            new_name='numero_bc',
        ),
        migrations.RenameField(
            model_name='bondelivraison',
            old_name='nummero_bl',
            new_name='numero_bl',
        ),
    ]
